using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExamenProgracionII_PrimerExamen
{
    class ClsPlantilla
    {
        public void formato()
        {

            //**************************************
            //Formato de ventana

            Console.SetCursorPosition(1, 1);
                Console.WriteLine("+");
                Console.SetCursorPosition(1, 2);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 3);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 4);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 5);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 6);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 7);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 8);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 9);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 10);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 11);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 12);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 17);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 19);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 20);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 21);
                Console.WriteLine("|");
                Console.SetCursorPosition(1, 22);
                Console.WriteLine("+");

                Console.SetCursorPosition(76, 1);
                Console.WriteLine("+");
                Console.SetCursorPosition(76, 2);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 3);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 4);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 5);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 6);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 7);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 8);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 9);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 10);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 11);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 12);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 13);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 14);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 15);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 16);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 17);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 18);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 19);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 20);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 21);
                Console.WriteLine("|");
                Console.SetCursorPosition(76, 22);
                Console.WriteLine("+");

                Console.SetCursorPosition(2, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(3, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(4, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(5, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(6, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(7, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(8, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(9, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(10, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(11, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(12, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(13, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(14, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(15, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(16, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(17, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(18, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(19, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(20, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(21, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(22, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(23, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(24, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(25, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(26, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(27, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(28, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(29, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(30, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(31, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(32, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(33, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(34, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(35, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(36, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(37, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(38, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(39, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(40, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(41, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(42, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(43, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(44, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(45, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(46, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(47, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(48, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(49, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(50, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(51, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(52, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(53, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(54, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(55, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(56, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(57, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(58, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(59, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(60, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(61, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(62, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(63, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(64, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(65, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(66, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(67, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(68, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(69, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(70, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(71, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(72, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(73, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(74, 1);
                Console.WriteLine("-");
                Console.SetCursorPosition(75, 1);
                Console.WriteLine("-");

                Console.SetCursorPosition(2, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(3, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(4, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(5, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(6, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(7, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(8, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(9, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(10, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(11, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(12, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(13, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(14, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(15, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(16, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(17, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(18, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(19, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(20, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(21, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(22, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(23, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(24, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(25, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(26, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(27, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(28, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(29, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(30, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(31, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(32, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(33, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(34, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(35, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(36, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(37, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(38, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(39, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(40, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(41, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(42, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(43, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(44, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(45, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(46, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(47, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(48, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(49, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(50, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(51, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(52, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(53, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(54, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(55, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(56, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(57, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(58, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(59, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(60, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(61, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(62, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(63, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(64, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(65, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(66, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(67, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(68, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(69, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(70, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(71, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(72, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(73, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(74, 22);
                Console.WriteLine("-");
                Console.SetCursorPosition(75, 22);
                Console.WriteLine("-");

                //**************************************
            



            Console.SetCursorPosition(22, 3);
            Console.WriteLine("-Sistema Pago de Servicios Publicos-");
            Console.SetCursorPosition(25, 4);
            Console.WriteLine("Tienda Monge - Ingreso de Datos");
        }
    }
}
